# Generated by Django 4.2.7 on 2025-10-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sms.campaign'),
        ),
    ]
