# Generated by Django 4.2.7 on 2025-12-17 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_smsmessage_user_smsrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_universal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('teacher', 'name')},
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', True)), fields=('name',), name='unique_universal_group_name'),
        ),
    ]
