# Generated by Django 5.1.5 on 2025-12-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_group_is_universal_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrecipient',
            name='error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
