# Generated by Django 4.2.7 on 2025-12-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_smsrecipient_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms.template'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='title',
            field=models.CharField(blank=True, help_text='Template title at time of sending', max_length=255, null=True),
        ),
    ]
