# Generated by Django 5.1.5 on 2025-12-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_smsmessage_template_smsmessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrecipient',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsrecipient',
            name='personalized_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
