SMS_ERROR_CODES = {
    "0": "Success (message successfully submitted; check message parameter for message id and parts)",
    "001": "Account details cannot be blank",
    "003": "SenderId cannot be blank",
    "004": "Message cannot be blank",
    "005": "Message properties cannot be blank",
    "006": "Internal Server Error Occurred",
    "007": "Invalid ApiCredentials",
    "009": "User account locked, contact your Administrator",
    "010": "Unauthorized API access",
    "011": "Unauthorized IP address",
    "012": "Message length violation",
    "013": "Invalid mobile numbers",
    "015": "Invalid SenderId",
    "017": "Invalid groupid",
    "018": "Group Not Allowed in BulkSMS",
    "019": "Invalid schedule date",
    "020": "Message or mobile number cannot be blank",
    "023": "Parameter missing",
    "024": "Invalid template or template mismatch",
    "026": "Invalid date range",
    "028": "Group not found",
    "029": "Record already exist",
    "033": "Queue Connection Closed",
    "034": "Unable to create campaign at this time please try again later",
    "036": "Error While Publishing DLR",
    "041": "Report Not Found",
    "042": "Max Mobile Number limit exceeded",
    "043": "Invalid Validity Period",
    "1025": "Insufficient Credits",
    "1026": "Invalid Template while message processing",
    "1029": "Invalid SenderId while message processing",
    "1044": "Spam Message Detected",
    "1047": "User account inactive",
    "1081": "Country not found in master data",
    "1082": "Network not found",
    "1083": "Price not found",
    "1084": "Expired",
    "1085": "Route not found",
    "1086": "Failover route not found",
    "1087": "Failover expired",
    "1088": "Failover price not found",
    "1089": "Failover failed",
    "1090": "Account Validity Expired",
    "1091": "Encoding Error",
    "1092": "OA/DA Error",
    "1093": "Queue Message Expired",
    "1094": "Invalid HTTP gateway config",
    "1095": "HTTP Request Exception"
}
